{
 "title": "Статистика",
 "time": { "from": "now-2m", "to": "now" },
 "panels": [
  { "title": "Транзакции", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Количество мошеннических транзакций",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fraud_transaction_counter_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество валидных транзакций",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "valid_transaction_counter_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество ошибочных транзакций",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "error_transaction_counter_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество транзакций по категориям",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(category_count{t_category=\"AUTO\"}[$__interval])",
     "legendFormat": "{{Авто}}"
    },
    {
     "expr": "sum_over_time(category_count{t_category=\"BOOKS\"}[$__interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time(category_count{t_category=\"CLOTHES\"}[$__interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time(category_count{t_category=\"ELECTRONICS\"}[$__interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time(category_count{t_category=\"ENTERTAINMENT\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Категория \"Авто\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Количество операций",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum_over_time(category_count{t_category=\"AUTO\"}[$__interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Максимальная сумма покупки",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max_over_time(category_max_amount{t_category=\"AUTO\"}[$__interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Минимальная сумма покупки",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min_over_time(category_min_amount{t_category=\"AUTO\"}[$__interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Среднее",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$A / $B", "type": "math" }
     ]
    }
   ]
  },
  {
   "title": "Категория \"Книги\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "Количество операций",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(category_count{t_category=\"BOOKS\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Максимальная сумма покупки",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(category_max_amount{t_category=\"BOOKS\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Минимальная сумма покупки",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(category_min_amount{t_category=\"BOOKS\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Категория \"Одежда\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "Количество операций",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(category_count{t_category=\"CLOTHES\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Максимальная сумма покупки",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(category_max_amount{t_category=\"CLOTHES\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Минимальная сумма покупки",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(category_min_amount{t_category=\"CLOTHES\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Категория \"Электроника\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Количество операций",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum_over_time(category_count{t_category=\"ELECTRONICS\"}[$__interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Максимальная сумма покупки",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max_over_time(category_max_amount{t_category=\"ELECTRONICS\"}[$__interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Минимальная сумма покупки",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min_over_time(category_min_amount{t_category=\"ELECTRONICS\"}[$__interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Среднее",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$A / $B", "type": "math" }
     ]
    }
   ]
  },
  {
   "title": "Категория \"Развлечения\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Количество операций",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum_over_time(category_count{t_category=\"ENTERTAINMENT\"}[$__interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Максимальная сумма покупки",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max_over_time(category_max_amount{t_category=\"ENTERTAINMENT\"}[$__interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Минимальная сумма покупки",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min_over_time(category_min_amount{t_category=\"ENTERTAINMENT\"}[$__interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Среднее",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$A / $B", "type": "math" }
     ]
    }
   ]
  }
 ]
}